### ISSUE TITLE
Support (Inbuilt)[] - Value type missmatch with iterator over elements, equals equation (where param) codegen

### ISSUE THREAD

**Issue by yoroshikun** [Brendonovich/prisma-client-rust#50]
First of all, thanks for working on this project!

I seem to be getting a pretty generic value type mismatch in the generated prisma -> rust codegen 

```
a value of type `std::vec::Vec<prisma_client_rust::query_core::QueryValue>` cannot be built from an iterator over elements of type `prisma_client_rust::prisma_models::PrismaValue`

value of type `std::vec::Vec<prisma_client_rust::query_core::QueryValue>` cannot be built from `std::iter::Iterator<Item=prisma_client_rust::prisma_models::PrismaValue>`

help: the trait `std::iter::FromIterator<prisma_client_rust::prisma_models::PrismaValue>` is not implemented for `std::vec::Vec<prisma_client_rust::query_core::QueryValue>`rustc(E0277)
```

These errors pretty much exclusively appear under the equals equation something like
```rust
                Self::AtkLevelsEquals(value) => (
                    "ATKLevels".to_string(),
                    SerializedWhereValue::Object(vec![(
                        "equals".to_string(),
                        QueryValue::List(
                            value
                                .into_iter()
                                .map(|v| PrismaValue::Json(serde_json::to_string(&v).unwrap())) // <--- error here
                                .collect(),
                        ),
                    )]),
                ),
```

#### Edit
Almost immediately after posting this i noticed the correlation. Seems to happen on `Inbuilt[]` types such as `String[] | Float[] | int[]` etc
Have reflected it in the title

**Comment by Brendonovich** [comment]
Ah, looks like I haven't added a `.into()` after the `PrismaValue` is constructed [here](https://github.com/Brendonovich/prisma-client-rust/blob/13d93966debf0d4ead83b8f0fa1085b4fb5a31e4/cli/src/generator/ast/dmmf.rs#L396).

**Comment by yoroshikun** [comment]
Commit `7b103ca7e422d2d5a8935818407fc0023f1b3ab8` might be missing the into(). 
in other notes it also tends to not create a converter.

eg.
```rust
SetParam::SetAtkLevels(value) => ("ATKLevels".to_string(), converter), <-- this converter value is not made
```

**Comment by Brendonovich** [comment]
`c1b97513b67e1b3c15d77d3cf120a50fd7a03ecd` should fix the `into` not being added, what do you mean about the converter not being created?

**Comment by yoroshikun** [comment]
this partially fixes it,

To explain more i get 2 errors for any schema item with the type [] that are inbuilt types (not other tables).

```rust
                SetParam::SetPossibleValuesFormat(value) => {
                    ("possibleValuesFormat".to_string(), converter) // <-- the converter here is not in scope, and i cannot find it, thinking it has just not been created?
                }
                SetParam::PushPossibleValuesFormat(value) => (
                    "possibleValuesFormat".to_string(),
                    QueryValue::Object(
                        vec![("push".to_string(), PrismaValue::String(value).into())] // <-- Getting error two below, type missmatch
                            .into_iter()
                            .collect(),
                    ),
                ),
   ```
   
   Error 1:
   ```
   cannot find value `converter` in this scope

    not found in this scoperustc(E0425)
   ```
   
   Error 2: 
   ```
   mismatched types

expected struct `std::string::String`, found struct `std::vec::Vec`

note: expected struct `std::string::String`
         found struct `std::vec::Vec<std::string::String>`rustc(E0308)
   ```

**Comment by Brendonovich** [comment]
Error 1 is me being silly and forgetting a #

Error 2 is lists not being treated properly

Try `b3c93e9eced80e259578e9a916531940c3876ad5`

**Comment by yoroshikun** [comment]
Much closer now,

Had to use commit `89df3982f80a68949f4f82d35a218838d56afc6b` as `b3c93e9eced80e259578e9a916531940c3876ad5` version bump panicked as it could not find the binary for my machine
```
Downloading https://prisma-photongo.s3-eu-west-1.amazonaws.com/prisma-cli-3.13.0-darwin.gz to /Users/yoroshi/Library/Caches/prisma/binaries/cli/3.13.0/prisma-cli-darwin
thread 'main' panicked at 'received code 404 Not Found from https://prisma-photongo.s3-eu-west-1.amazonaws.com/prisma-cli-3.13.0-darwin.gz', /Users/yoroshi/.cargo/git/checkouts/prisma-client-rust-fa967aa5ad0ec391/b3c93e9/cli/src/binaries/mod.rs:142:9
```

Still getting issues with Error 2 listed above, expecting non vec in generated code.
This time only for the "push" query.

**Comment by Brendonovich** [comment]
I haven't been able to replicate Error 2. Can you please provide a schema that generates the invalid code?

**Comment by yoroshikun** [comment]
Hi i was able to reproduce it with a modified example schema.
extra notes: these primitives are only available not using the sqlite adapter.

```prisma
generator client {
  provider = "cargo prisma"
  output   = "../src/prisma.rs"
}

// Array primitives only available in postgresql
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id String @id

  updatedAt   DateTime @default(now()) @updatedAt
  displayName String

  usernames String[] // These few lines generate the issues
  ids       Int[] // This one does too
  floats    Float[] // This one too
  bools     Boolean[] // This one too

  jsons Json[] // This one is fine

  posts Post[] // This is normal
}

model Post {
  id      String @id
  content String
  user    User   @relation(fields: [userId], references: [id])
  userId  String
}

```

**Comment by Brendonovich** [comment]
@yoroshikun I think I got it in `3cde8feb55a2efe7877ab57625c54f865ebf37c7`

**Comment by yoroshikun** [comment]
@Brendonovich This looks like it solved this issue!
